### ISSUE TITLE
[BUG] No schema.pbtxt File is being generated from NVTabular workflow

### ISSUE THREAD

**Issue by thomaspzollo** [NVIDIA-Merlin/NVTabular#1385] opened 2022-02-07 12:31 UTC
**Describe the bug**
I am trying to generate schema.pbtxt file from NVTabular workflow using the same exact script posted here: https://github.com/NVIDIA-Merlin/NVTabular/issues/1156

```
NUM_ROWS = 1000
long_tailed_item_distribution = np.clip(np.random.lognormal(3., 1., NUM_ROWS).astype(np.int32), 1, 50000)

# generate random item interaction features 
df = pd.DataFrame(np.random.randint(70000, 80000, NUM_ROWS), columns=['session_id'])
df['item_id'] = long_tailed_item_distribution

# generate category mapping for each item-id
df['category'] = pd.cut(df['item_id'], bins=334, labels=np.arange(1, 335)).astype(np.int32)
df['timestamp/age_days'] = np.random.uniform(0, 1, NUM_ROWS)
df['timestamp/weekday/sin']= np.random.uniform(0, 1, NUM_ROWS)

# generate day mapping for each session 
map_day = dict(zip(df.session_id.unique(), np.random.randint(1, 10, size=(df.session_id.nunique()))))
df['day'] =  df.session_id.map(map_day)

# Categorify categorical features
categ_feats = ['session_id', 'item_id', 'category'] >> nvt.ops.Categorify(start_index=1)

# Define Groupby Workflow
groupby_feats = categ_feats + ['day', 'timestamp/age_days', 'timestamp/weekday/sin']

# Groups interaction features by session and sorted by timestamp
groupby_features = groupby_feats >> nvt.ops.Groupby(
    groupby_cols=["session_id"], 
    aggs={
        "item_id": ["list", "count"],
        "category": ["list"],     
        "day": ["first"],
        "timestamp/age_days": ["list"],
        'timestamp/weekday/sin': ["list"],
        },
    name_sep="-")

# Select and truncate the sequential features
sequence_features_truncated = (groupby_features['category-list', 'item_id-list', 
                                          'timestamp/age_days-list', 'timestamp/weekday/sin-list']) >> \
                            nvt.ops.ListSlice(0,20) >> nvt.ops.Rename(postfix = '_trim')

# Filter out sessions with length 1 (not valid for next-item prediction training and evaluation)
MINIMUM_SESSION_LENGTH = 2
selected_features = groupby_features['item_id-count', 'day-first', 'session_id'] + sequence_features_truncated
filtered_sessions = selected_features >> nvt.ops.Filter(f=lambda df: df["item_id-count"] >= MINIMUM_SESSION_LENGTH)


workflow = nvt.Workflow(filtered_sessions)
dataset = nvt.Dataset(df, cpu=False)
# Generating statistics for the features
workflow.fit(dataset)
workflow.transform(dataset).to_parquet(
    './schema',
    out_files_per_proc=1,
)

schema_path = Path('./schema')
proto_schema = Schema.read_protobuf(schema_path / "schema.pbtxt")
```

**Expected behavior**
When I check the contents of the ./schema folder, the only files placed in there are:
`_file_list.txt  _metadata  _metadata.json  part_0.parquet`

**Comment by rnyak** [comment] 2022-02-07 13:37
@thomaspzollo thanks for your question.  I ran the code snippet aboce and I can see the `schema.pbtxt` in the `schema` folder. So I could not reproduce your issue.

Can you tell us what's your env? which NVTabular version are you using? If you are using docker image, you can pull the latest containers as follow:
```
 docker pull nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.02
```
OR
```
 docker pull nvcr.io/nvidia/merlin/merlin-pytorch-training:22.02
```
If you are in a conda env, please be sure your NVTabular `main` branch is the latest. You can pull the latest as follows:

```
git checkout main && git pull origin main
pip install -e .
```
Hope that helps.

**Comment by alexanderDoria** [comment] 2022-02-08 08:51
Hey @rnyak, I work with @thomaspzollo. We're using the installation instructions found [here](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/docs/source/resources/cloud_integration.md#databricks) and working with Databricks. We're using the `0.6.1` line referenced in the instructions as well. However, it's starting to become difficult to upgrade NVTabular because the rest of the dependencies begin to change. Currently, I'm seeing issues with libllvmlite after upgrading NVTabular to `0.8.0`.

**Comment by thomaspzollo** [comment] 2022-02-10 20:27
Thanks for getting back @jperez999!  We basically need a container for Databricks that will be able to run demos notebooks 1+2 from this directory: https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based

I don't think we're 100% what the requirements list would be, but practically that is what we are trying to achieve.

**Comment by alexanderDoria** [comment] 2022-02-10 20:40
Tom is right. I also want to emphasize that it's not just importing the libraries that we need (since we've gotten that far with the original installation instructions), it's that the libraries should ideally be functioning as expected in the tutorials. (re: the original bug in this post). thanks again for the help!

**Comment by jperez999** [comment] 2022-02-10 22:01
@koyuki-nakamori @thomaspzollo @alexanderDoria the following dockerfile has been verified to create a container that runs all 3 notebooks in the transformers4rec getting started example. When we get access to databricks platform we will also test there. Figured I could give it to you in the mean time to test yourself.
```
FROM databricksruntime/gpu-conda:cuda11
  
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION='python'
RUN apt update -y && \
    apt install -y build-essential && \
    apt install -y --no-install-recommends software-properties-common
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin  && \
    mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600  && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub  && \
    add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"  && \
    apt-get update -y && apt install -y --allow-change-held-packages git python3.8 python3-setuptools wget openssl libssl-dev zlib1g-dev libcudnn8 libcudnn8-dev
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh && bash Miniconda3-py38_4.10.3-Linux-x86_64.sh -b
RUN conda create -y -n rapids -c rapidsai -c nvidia -c conda-forge rapids=21.12 python=3.8 cudatoolkit=11.0
SHELL ["conda", "run", "--no-capture-output", "-n", "rapids", "/bin/bash", "-c"]
RUN pip install tensorflow==2.7.0
RUN pip install pybind11 pynvml pytest graphviz sklearn scipy matplotlib nvidia-pyindex tritonclient[all] grpcio-channelz nvtx cachetools typing_extensions fastavro
RUN git clone https://github.com/rapidsai/asvdb.git build-env && \
    pushd build-env && \
      python setup.py install && \
    popd && \
    rm -rf build-env
RUN pip install pandas sklearn ortools pydot cache purge
RUN pip install numpy==1.20.3
RUN pip install transformers4rec[all]
```

**Comment by alexanderDoria** [comment] 2022-02-14 19:08
@jperez999 thank you! testing it today

**Comment by alexanderDoria** [comment] 2022-02-15 09:23
I'm getting the following error: `java.lang.Exception: Cannot run program &quot;virtualenv&quot; (in directory &quot;/local_disk0/pythonVirtualEnvDirs&quot;): error=2, No such file or directory`. I suspect it has to do with the `SHELL` command in the Dockerfile. I'm getting `Failure starting repl. Try detaching and re-attaching the notebook.` in Databricks. 

Currently experimenting with modifying that command, but let me know if you have an immediate solution.

**Comment by alexanderDoria** [comment] 2022-02-22 22:07
Update: I was able to run notebook cells using the image after some tweaks to the Dockerfile. The original bug in this post has been resolved. However, now I'm trying to run through the tutorials [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based), but neither PyTorch or TensorFlow are working as expected.

For the PyTorch version, I'm running into: `CUDA error: out of memory` when running
```
trainer = Trainer(
    model=model,
    args=train_args,
    schema=schema,
    compute_metrics=True,
)
```

For TensorFlow, I'm running into `Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_OUT_OF_MEMORY` when trying to run `from nvtabular.loader.tensorflow import KerasSequenceLoader`.

It feels like it has to do with version incompatibilities with CUDA. 

For instance, with Keras, the following also results in OOM: 

```
import torch 

foo = torch.tensor([1,2,3])
foo = foo.to('cuda')
```

Going to be looking into the versions now.

**Comment by jperez999** [comment] 2022-03-03 18:29
@alexanderDoria  sorry we haven't been able to help out any further yet. We are working on getting access to the databricks platform. Once we have access, we should be able to help out a little more.

**Comment by rnyak** [comment] 2022-03-10 12:35
> Tom is right. I also want to emphasize that it's not just importing the libraries that we need (since we've gotten that far with the original installation instructions), it's that the libraries should ideally be functioning as expected in the tutorials. (re: the original bug in this post). thanks again for the help!

@alexanderDoria @thomaspzollo  the original issue is not a bug. It happens because of the old version on NVTabular you were using.  In addition, you cannot get schema generated with the script above you shared. We used manually generated `schema.pb` files for the examples in the notebooks. You need to do something like that (this is just an example, adapt it for your workflow) to add tags in the schema.pbtxt:

````
cat_features = ['movieId] >> nvt.ops.Categorify()
feats_item = cat_features['movieId'] >> ops.AddMetadata(tags=["item_id", "item"])
feats_user = cat_features['userId'] >> ops.AddMetadata(tags=[ "user_id", "user"])
feats_genres = cat_features['genres'] >> ops.AddMetadata(tags=["item"])

feats_target = (nvt.ColumnSelector(["rating"]) >> 
           ops.LambdaOp(lambda col: (col > 3).astype("int32")) >> 
           ops.AddMetadata(tags=["binary_classification", "target"]) >> 
           nvt.ops.Rename(name ='rating_binary')
          )
target_orig = ['rating'] >> ops.AddMetadata(tags=["regression", "target"])

workflow = nvt.Workflow(cat_features + feats_item + feats_user + feats_genres  + target_orig + feats_target )
train_dataset = nvt.Dataset([os.path.join(INPUT_DATA_DIR, "train.parquet")])
workflow.fit(train_dataset)

workflow.transform(train_dataset).to_parquet(
    output_path=os.path.join(INPUT_DATA_DIR, "train"),
    out_files_per_proc=1,
    shuffle=False,
)
```

Then go to os.path.join(INPUT_DATA_DIR, "train") folder, you will see the schema.pbtxt file.

Hope that helps.

**Comment by rnyak** [comment] 2022-03-10 12:50
> Update: I was able to run notebook cells using the image after some tweaks to the Dockerfile. The original bug in this post has been resolved. However, now I'm trying to run through the tutorials [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/getting-started-session-based), but neither PyTorch or TensorFlow are working as expected.
> 
> For the PyTorch version, I'm running into: `CUDA error: out of memory` when running
> 
> ```
> trainer = Trainer(
>     model=model,
>     args=train_args,
>     schema=schema,
>     compute_metrics=True,
> )
> ```
> 
> For TensorFlow, I'm running into `Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_OUT_OF_MEMORY` when trying to run `from nvtabular.loader.tensorflow import KerasSequenceLoader`.
> 
> It feels like it has to do with version incompatibilities with CUDA.
> 
> For instance, with Keras, the following also results in OOM:
> 
> ```
> import torch 
> 
> foo = torch.tensor([1,2,3])
> foo = foo.to('cuda')
> ```
> 
> Going to be looking into the versions now.

@alexanderDoria can you share cuda versions please?  also what does `nvcc --version` print out?  Thanks.

**Comment by jperez999** [comment] 2022-03-10 19:10
@alexanderDoria can you also share the `nvidia-smi` output for the instance hitting this problem

**Comment by alexanderDoria** [comment] 2022-03-15 20:00
hey @jperez999 and @rnyak, sorry for the late response. I'm happy to inform that I got it working. The most recent issue was running out of memory (which was solved by increasing the size of the cluster). We also had an issue with NVTabular/T4R which was solved by downgrading NVTabular. I'm able to run the tutorial cells now.

Let me know if you'd like me to give more info on anything.

**Comment by karlhigley** [comment] 2022-03-15 20:02
We'd be curious to know what issue was resolved by downgrading NVT (if it's easy to reproduce), but otherwise just glad to hear you got it working! 👍🏻

**Closed by karlhigley** 2022-03-15 20:02 UTC
Labels: bug

**Comment by alexanderDoria** [comment] 2022-03-15 20:16
Hey @karlhigley, sure, I got `no module named nvtabular.io.dataset` when running the training cells in the 2nd getting-started notebook until I downgraded to `nvtabular==0.10.0`

**Comment by karlhigley** [comment] 2022-03-15 21:09
Ah, that makes sense! As we've expanded the Merlin ecosystem, we've been moving a lot of code out of NVTabular into other libraries, and it sounds like our attempts to maintain backwards compatibility weren't entirely successful. Thanks!
