### ISSUE TITLE
[BUG] Train Test Split Errors out in Multi-GPU Movielens TF and Pytorch Notebooks

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/NVTabular#1287] opened 2021-12-01 22:39 UTC
**Describe the bug**
Train Test Split Errors out in Multi-GPU Movielens [TF](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-TensorFlow.ipynb) and [Pytorch](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb) Notebooks

**Steps/Code to reproduce bug**
#### Split into train and validation datasets
```
ratings = cudf.read_csv(pathlib.Path(BASE_DIR, "ml-25m", "ratings.csv"))
ratings = ratings.drop("timestamp", axis=1)
train, valid = train_test_split(ratings, test_size=0.2, random_state=42)
train.to_parquet(pathlib.Path(BASE_DIR, "train.parquet"))
valid.to_parquet(pathlib.Path(BASE_DIR, "valid.parquet"))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_280/2455867955.py in <module>
      1 ratings = cudf.read_csv(pathlib.Path(BASE_DIR, "ml-25m", "ratings.csv"))
      2 ratings = ratings.drop("timestamp", axis=1)
----> 3 train, valid = train_test_split(ratings, test_size=0.2, random_state=42)
      4 train.to_parquet(pathlib.Path(BASE_DIR, "train.parquet"))
      5 valid.to_parquet(pathlib.Path(BASE_DIR, "valid.parquet"))

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py in train_test_split(test_size, train_size, random_state, shuffle, stratify, *arrays)
   2443         train, test = next(cv.split(X=arrays[0], y=stratify))
   2444 
-> 2445     return list(
   2446         chain.from_iterable(
   2447             (_safe_indexing(a, train), _safe_indexing(a, test)) for a in arrays

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py in <genexpr>(.0)
   2445     return list(
   2446         chain.from_iterable(
-> 2447             (_safe_indexing(a, train), _safe_indexing(a, test)) for a in arrays
   2448         )
   2449     )

/usr/local/lib/python3.8/dist-packages/sklearn/utils/__init__.py in _safe_indexing(X, indices, axis)
    374 
    375     if hasattr(X, "iloc"):
--> 376         return _pandas_indexing(X, indices, indices_dtype, axis=axis)
    377     elif hasattr(X, "shape"):
    378         return _array_indexing(X, indices, indices_dtype, axis=axis)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/__init__.py in _pandas_indexing(X, key, key_dtype, axis)
    216         # using take() instead of iloc[] ensures the return value is a "proper"
    217         # copy that will not raise SettingWithCopyWarning
--> 218         return X.take(key, axis=axis)
    219     else:
    220         # check whether we should index with loc or iloc

TypeError: take() got an unexpected keyword argument 'axis'
```

**Expected behavior**
train test split to go through without any errors

**Environment details (please complete the following information):**
  merlin-tensorflow-training:21.11 and merlin-pytorch-training:21.11 NGC Containers

**Comment by EvenOldridge** [comment] 2021-12-01 22:56
Thanks for posting.  This is a duplicate of https://github.com/NVIDIA-Merlin/NVTabular/issues/1287 and related to sklearn data formats.  We're planning to replace it with something GPU based.

**Closed by EvenOldridge** 2021-12-01 22:56 UTC
Labels: bug

**Comment by kshitizgupta21** [comment] 2021-12-01 23:01
@EvenOldridge Do you mean this issue is a duplicate of different issue? Because issue 1287 is this current issue.

**Comment by rnyak** [comment] 2021-12-02 00:38
@kshitizgupta21 it is the duplicate of https://github.com/NVIDIA-Merlin/NVTabular/issues/1258. I will update the notebooks.

**Comment by EvenOldridge** [comment] 2021-12-02 00:47
Sorry, copy paste error.  @rnyak thanks for linking to the correct issue.
